language: node_js
node_js:
  - "6.9.4"
before_script:
  - npm install -g gulp
script: gulp test
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
